name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: CyberSecurityChatbotPOE

    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: CyberSecurityChatbotPOE

    - name: Run Tests
      run: dotnet test --no-build --verbosity normal
      working-directory: CyberSecurityChatbotPOE
      continue-on-error: true
